config/routes.rb
Rails.application.routes.draw do

  resources :expenses
  resources :categories
  resources :incomes
  get 'home/index'

  get 'welcome/index'
  
  root 'home#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get '/auth/:provider/callback', to: 'sessions#createFacebook'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  #has_many :incomes
  validates :email, presence: true, uniqueness:true #gli utenti devono essere univoci
  has_secure_password #verifico che le due password inserite nel form di registrazione siano uguali

	class << self
	    def from_omniauth(auth_hash)
	      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
	      if auth_hash['info']['email']
	      	user.email = auth_hash['info']['email'] #ho messo name perchè la mail non riesco a prenderla e mi da errore. da vedere con davide
	      else
	      	user.email = auth_hash['info']['name']
	      end
	      user.password = "ppppp"
	      user.name = auth_hash['info']['name']
	      user.location = auth_hash['info']['location']
	      user.image_url = auth_hash['info']['image']
	      user.url = auth_hash['info']['urls'][user.provider.capitalize]
	      user.save!
	      user
	    end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create] #skip all method except new e create

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.uid = Digest::MD5.hexdigest(@user.email)
    @user.provider = "Email Registration"
    @user.image_url = "https://cdn3.iconfinder.com/data/icons/rcons-user-action/32/boy-512.png"

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        #redirect_to welcome_index_url, alert: "Welcome!"
        format.html { redirect_to welcome_index_url }
        #format.json { render :show, status: :created, location: @user }
      else
        #redirect_to home_index_url
        format.html { redirect_to home_index_url, notice: "Error: this user could'd be alrady created." }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-default'%>
<%= link_to 'Back', welcome_index_path, class: 'btn btn-default'%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: 'btn btn-default' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>