config/routes.rb
Rails.application.routes.draw do

  resources :expenses
  resources :categories
  resources :incomes
  get 'home/index'

  get 'welcome/index'
  
  root 'home#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get '/auth/:provider/callback', to: 'sessions#createFacebook'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
	#belongs_to :user
	#has_one :category
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.where(users_id: session[:user_id]).order("date": :desc) #take all incomes of the user and order it DESC
    #@category = Category.find(2)
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
    @income = Income.where(id: params[:id], users_id: session[:user_id]).first
    
      if !@income
        respond_to do |format|
          format.html { redirect_to incomes_url, notice: "You can't see this income with id #{params[:id]}." }
        end
      end
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @user = User.find_by(id: session[:user_id])
    @income = Income.new(income_params)

    @income.users_id = @user.id

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:user, :amount, :categories_id, :indispensable, :description, :date)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(income) do |f| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.collection_select(:categories_id, Category.where(kind: ["incomes", "both"]), :id, :title) %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incomes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount %></td>
        <td><%= Category.find(income.categories_id).title %></td>
        <td><%= income.description %></td>
        <td><%= income.date %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path, class: 'btn btn-default' %>
<%= link_to 'Back', welcome_index_path, class: 'btn btn-default' %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path, class: 'btn btn-default' %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@income.categories_id).title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @income.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @income.date %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>